name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Run every morning at 01:00 to detect flakiness and broken dependencies
    - cron: '0 1 * * *'
      timezone: "Europe/Zurich"

jobs:
  jazzy:
    uses: Duatic/ci-workflows/.github/workflows/ros_ici.yml@1cf0d48d0525938b882071dc5679b69f29c06679
    with:
      ros_distro: jazzy
      ros_repo: main
      ref_for_scheduled_build: main
    secrets: inherit

  other_distros:
    needs: jazzy # gate: only run if jazzy succeeded
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ros_distro: kilted, ros_repo: main }
          - { ros_distro: lyrical, ros_repo: main }
          - { ros_distro: rolling, ros_repo: testing }
    uses: Duatic/ci-workflows/.github/workflows/ros_ici.yml@1cf0d48d0525938b882071dc5679b69f29c06679
    with:
      ros_distro: ${{ matrix.ros_distro }}
      ros_repo: ${{ matrix.ros_repo }}
      ref_for_scheduled_build: main
    secrets: inherit

  pre-commit:
    uses: Duatic/ci-workflows/.github/workflows/pre-commit.yml@1cf0d48d0525938b882071dc5679b69f29c06679
